# Generated by Django 5.1.1 on 2024-10-04 17:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='author',
            name='published_books',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
